server {
    listen 80;
    server_name kiraaura.com;
    root /var/www/kiraaura.com;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # For Let's Encrypt HTTP challenge
    location /.well-known/acme-challenge/ {
        root /var/www/kiraaura.com;
    }
}

