server {
    listen 80;
    server_name tegridy.agency;
    root /var/www/tegridy.agency;

    # Лендинг для моделей — статика из /var/www/tegridy.agency/model
    location = /model {
        return 301 /model/;
    }
    location /model/ {
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Лендинг для операторов — статика из /var/www/tegridy.agency/operator
    location = /operator {
        return 301 /operator/;
    }
    location /operator/ {
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Академия операторов — статика из /var/www/tegridy.agency/base
    location = /base {
        return 301 /base/;
    }
    location /base/ {
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Optional: Catch-all for other paths (can redirect to a default page or show 404)
    location / {
        # You might want to return a 404 or redirect elsewhere
        return 404;
        # try_files $uri $uri/ =404;
    }
} 
