server {
    listen 80;
    server_name tegridy.agency;
    root /var/www/tegridy.agency;

    # Redirect for /model
    location = /model {
        return 301 https://form.asana.com/?k=_i2aW1PvQTtSM5ldLjA9xA&d=1206405818803094;
    }

    # Redirect for /operator
    location = /operator {
        return 301 https://form.asana.com/?k=06TJIp0HyieE3jba-MlwBA&d=1206405818803094;
    }

    # Академия операторов — статика из /var/www/tegridy.agency/base
    location = /base {
        return 301 /base/;
    }
    location /base/ {
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Optional: Catch-all for other paths (can redirect to a default page or show 404)
    location / {
        # You might want to return a 404 or redirect elsewhere
        return 404;
        # try_files $uri $uri/ =404;
    }
} 
